### ISSUE TITLE
Add score grouping to fellows reviews

### ISSUE THREAD

**Issue by Bullrich** [paritytech/review-bot#110]
Per proposed in polkadot-fellows/runtimes#93 we need to have a slight change in the review-bot type `fellows`.

The new solution will keep the old behaviour, with a slight modification:

It will still request a minimum amount of reviews of a given rank, but it will now have a _minimum score_ that it must be achieved also to be approved, allowing more flexible reviews from lower ranks.

For this, a new field named `score` will be introduced, this will contain a list of all the available dans and their score.

When individuals approve a PR, their dan's `score` will count towards the total required score.

For example:

```yml
score:
  dan1: 1
  dan2: 2
  dan3: 5
  dan4: 9
  dan5: 10
  dan6: 15
rules:
  - name: CI Files
    condition:
      include:
        - ^\.github/.*
    type: fellows
    minRank: 3
    minApprovals: 1
    minScore: 18
```

This would work in the following way:

`CI Files` would require at least *one* approval from someone who is *dan 3 or greater*. And the combined value of all the approvals, defined in `minScore`, must get to 18.

So, in this case, a vote of a dan 6, would count 15 points. And we would still need 3 more points. Could either be from:
- 3 `dan 1`.
- 1 `dan2` and 1 `dan1`.
- 2 `dan2`.
- 1 `dan3` or greater.
