### ISSUE TITLE
Handle cases where amount of reviews is bigger than the amount of available users

### ISSUE THREAD

**Issue by Bullrich** [paritytech/review-bot#27]
This would handle the cases where it is impossible to fulfill the requirements.

Examples of impossible configs:
```yml
# the amount of required approvals is bigger than the amount of available users
min_approvals: 5
users:
  - user-1
  - user-2
  - user-3
```
or let's say that `team-1` only has 3 members:
```yml
# We would have the same problem here
min_approvals: 5
teams:
  - team-1
```
