### ISSUE TITLE
Ability to greenlight rule if author belongs to list

### ISSUE THREAD

**Issue by Bullrich** [paritytech/review-bot#66]
As requested by @the-right-joyce, let's add the ability that a rule can be ignored if the author belongs to a particular list (of teams).

Example proposal:
```yml
  - name: Opstooling
    condition:
      include:
        - '.*'
    type: basic
    ignoreFrom:
      - core-devs
    teams:
      - srlabs
```
